# Generated by Django 3.1.5 on 2021-01-30 16:00

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
                'default_related_name': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, default='', help_text='Будет отображено под заголовком', verbose_name='Короткое описание')),
                ('slug', models.SlugField(editable=False, help_text='Отображается в адресной строке', verbose_name='URL статьи')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers')),
                ('published_at', model_utils.fields.MonitorField(default=None, monitor='status', null=True, verbose_name='Дата публикации', when={1})),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Черновик'), (1, 'Опубликована')], default=0, verbose_name='Статус')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='', verbose_name='Текст статьи')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Автор статьи')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='news.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Статью',
                'verbose_name_plural': 'Статьи',
                'default_related_name': 'articles',
            },
        ),
    ]
