# Generated by Django 3.1.5 on 2021-01-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text='Отображается в адресной строке', verbose_name='URL путь'),
        ),
    ]
