# Generated by Django 3.1.5 on 2021-02-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='body_text',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(editable=False, help_text='Отображается в адресной строке', max_length=100, verbose_name='URL статьи'),
        ),
    ]
